apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tm
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      containers:
      - image: reg.dnt:5000/tomcat:7
        imagePullPolicy: IfNotPresent
        name: tm
